apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwebui-ollama
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ItsGaet/test.git'
    targetRevision: HEAD
    path: manifests/openwebui-ollama
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openwebui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
