---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pvc
  namespace: openwebui
spec:
  accessModes:
    - ReadWriteOnce  # Modifica se necessario (es. ReadWriteMany)
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn  # Assicurati che il nome sia corretto per Longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - containerPort: 8080
          env:
            - name: OLLAMA_BASE_URL
              value: "http://10.101.206.144:802"
          volumeMounts:
            - name: open-webui-storage
              mountPath: /app/backend/data
      volumes:
        - name: open-webui-storage
          persistentVolumeClaim:
            claimName: open-webui-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: openwebui
spec:
  type: NodePort
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
