apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - containerPort: 8080 # Porta interna del container
          env:
            - name: OLLAMA_BASE_URL
              value: "http://10.43.198.48:80" # Variabile d'ambiente configurata
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: openwebui
spec:
  type: NodePort
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080

