apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - containerPort: 8080 # Porta interna del container
          env:
            - name: OLLAMA_BASE_URL
              value: "http://10.101.206.144:802" # Variabile d'ambiente configurata
          volumeMounts:
            - name: open-webui-data
              mountPath: /app/backend/data # Mount del volume su /app/backend/data
      volumes:
        - name: open-webui-data
          emptyDir: {} # Volume di tipo emptyDir
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: openwebui
spec:
  type: NodePort
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
      nodePort: 32000
